[build]
  command = "hugo --gc --minify"
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.135.0"

[context.production.environment]
  HUGO_ENV = "production"
  NODE_ENV = "production"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

